/*const env = {
  ROOT: "dist/css/",
  CSSDIRECTORY: 'dist/css/',
  ROUTEPATH: '/',
  ENVIRONMENT: 'DEVELOPMENT',
  WEBSERVERADDRESS: "",
  SAVEAPPLICATIONMODULE: "FACTIGIS_DESA",
  SAVEAPPLICATIONNAME: 'REACT_AP_WEB_DESA'
}
*/
const env = {
  ROOT: "css/",
  CSSDIRECTORY: 'css/',
  ROUTEPATH: '/AP',
  ENVIRONMENT: 'PRODUCTION',
  WEBSERVERADDRESS: "http://gisred.chilquinta/AP/",
  SAVEAPPLICATIONMODULE: "FACTIGIS_DESA",
  SAVEAPPLICATIONNAME: 'REACT_FACTIGISVE_DESA'
}


export default env;
